version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-net:

  app:
    container_name: logger-service
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - DB_PORT=${MYSQLDB_LOCAL_PORT}
      - DB_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_DATABASE=$MYSQLDB_DATABASE
    networks:
      springboot-mysql-net:
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:8080"
      - "8000:8000"
    stdin_open: true
    tty: true


networks:
  springboot-mysql-net: