version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-net:

  app:
    container_name: logger-service
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - DB_PORT=${MYSQLDB_LOCAL_PORT}
      - DB_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_DATABASE=$MYSQLDB_DATABASE
    networks:
      springboot-mysql-net:
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:8080"
      - "8000:8000"
    stdin_open: true
    tty: true

  jmeter-node01:
    profiles: ["test"]
    depends_on:
      - app
    container_name: jmeter-node01
    image: justb4/jmeter
    networks:
      springboot-mysql-net:
    ports:
      - 1099
      - 50000
    volumes:
      - /input_data
      - /logs

  jmeter-node02:
    profiles: ["test"]
    depends_on:
      - app
    container_name: jmeter-node02
    image: justb4/jmeter
    networks:
      springboot-mysql-net:
    ports:
      - 1099
      - 50000
    volumes:
      - /input_data
      - /logs

  jmeter-node03:
    profiles: ["test"]
    depends_on:
      - app
    container_name: jmeter-node03
    image: justb4/jmeter
    networks:
      springboot-mysql-net:
    ports:
      - 1099
      - 50000
    volumes:
      - /input_data
      - /logs

  jmeter-master:
    profiles: ["test"]
    container_name: jmeter-master
    image: justb4/jmeter
    networks:
      springboot-mysql-net:
    ports:
      - 60000
    volumes:
      - ./jmeter/test_plan/scripts:/scripts
      - ./jmeter/logs:/logs
    entrypoint:
      - /var/lib/apache-jmeter/bin/jmeter
      - -n
      - -t
      - /scripts/logger_service_write_log_test.jmx
      - -l
      - /logs/results.csv
      - -j
      - /logs/jmeter.log
      - -LDEBUG
      - -R jmeter-node01,jmeter-node02,jmeter-node03



networks:
  springboot-mysql-net:















